import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  containerAuth: { flex: 1, backgroundColor: '#F3F4F6' },
  scrollContentAuth: { flexGrow: 1, justifyContent: 'center', padding: 20 },
  cardAuth: { backgroundColor: '#FFFFFF', borderRadius: 28, padding: 25, elevation: 5 },
  iconContainerAuth: { alignItems: 'center', marginBottom: 15 },
  iconCircleAuth: { width: 90, height: 90, borderRadius: 45, justifyContent: 'center', alignItems: 'center' },
  tituloAuth: { fontSize: 24, fontWeight: 'bold', color: '#111827', textAlign: 'center', marginBottom: 5 },
  subtituloAuth: { fontSize: 14, color: '#6B7280', textAlign: 'center', marginBottom: 25 },
  inputGroupAuth: { marginBottom: 18 },
  labelAuth: { fontSize: 13, fontWeight: '700', color: '#374151', marginBottom: 6 },
  inputContainerAuth: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
    borderRadius: 14,
    paddingHorizontal: 15,
    backgroundColor: '#F9FAFB',
  },
  inputIconAuth: { marginRight: 10 },
  inputAuth: { flex: 1, paddingVertical: 12, fontSize: 15 },
  eyeIconAuth: { padding: 5 },
  botaoEntrarAuth: { paddingVertical: 16, borderRadius: 14, alignItems: 'center', elevation: 2 },
  botaoEntrarTextAuth: { color: '#FFFFFF', fontWeight: 'bold', fontSize: 16 },
  linkEsqueciTextAuth: { fontSize: 13, fontWeight: '600', textAlign: 'center' },
  cadastroContainerAuth: { flexDirection: 'row', justifyContent: 'center', marginTop: 30 },
  cadastroTextAuth: { color: '#6B7280' },
  cadastroLinkAuth: { fontWeight: 'bold' },

  containerHome: { flex: 1, backgroundColor: '#F8FAFC' },
  blueHeader: {
    backgroundColor: '#1E3A8A',
    paddingTop: Platform.OS === 'ios' ? 40 : 50,
    paddingBottom: 25,
    paddingHorizontal: 25,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    elevation: 8,
  },
  headerContent: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  saudacaoHome: { color: '#BFDBFE', fontSize: 16 },
  nomeUsuarioHome: { color: '#FFF', fontSize: 24, fontWeight: 'bold', marginTop: 2 },
  badgeTipo: { backgroundColor: 'rgba(255,255,255,0.15)', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20 },
  badgeText: { color: '#FFF', fontSize: 11, fontWeight: 'bold', letterSpacing: 1 },

  contentScroll: { paddingHorizontal: 20 },
  secaoTitulo: { fontSize: 19, fontWeight: 'bold', color: '#1E293B', marginTop: 15, marginBottom: 15 },

  cardOracao: {
    backgroundColor: '#FFFBEB',
    borderColor: '#FDE68A',
    borderWidth: 1,
    borderRadius: 20,
    padding: 20,
    marginTop: 20,
    marginBottom: 10,
    elevation: 2,
  },
  linhaOracao: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 10 },
  tituloOracao: { fontSize: 18, fontWeight: 'bold', color: '#92400E', marginLeft: 10 },
  textoOracao: { fontSize: 16, color: '#B45309', fontStyle: 'italic', lineHeight: 24 },

  cardNovo: {
    backgroundColor: '#FFF',
    flexDirection: 'row',
    padding: 18,
    borderRadius: 22,
    alignItems: 'center',
    marginBottom: 14,
    elevation: 3,
  },
  cardIconCircle: { width: 55, height: 55, borderRadius: 18, justifyContent: 'center', alignItems: 'center' },
  cardInfoContent: { flex: 1, marginLeft: 15 },
  cardTituloInterno: { fontSize: 16, fontWeight: 'bold', color: '#334155' },
  cardTextoInterno: { fontSize: 14, color: '#64748B', marginTop: 3, lineHeight: 20 },

  btnVerMais: {
    backgroundColor: '#DBEAFE',
    marginTop: 5,
    padding: 15,
    borderRadius: 15,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
  },
  btnVerMaisText: { color: '#1E40AF', fontWeight: 'bold', fontSize: 14, marginRight: 5 },

  cardAlimentos: { backgroundColor: '#2563EB', borderRadius: 28, padding: 22, elevation: 6 },
  alimentosHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
  alimentosTitulo: { color: '#FFF', fontSize: 19, fontWeight: 'bold', marginLeft: 10 },
  alimentosDesc: { color: '#DBEAFE', fontSize: 14, marginBottom: 18, lineHeight: 20 },
  btnDoarAgora: {
    backgroundColor: '#10B981',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
    borderRadius: 16,
  },
  btnDoarText: { color: '#FFF', fontWeight: 'bold', fontSize: 15, marginRight: 10 },

  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', alignItems: 'center' },
  modalBox: { width: '85%', backgroundColor: '#FFF', borderRadius: 20, padding: 20, elevation: 10 },
  modalTitulo: { fontSize: 18, fontWeight: 'bold', color: '#1E293B', marginBottom: 15 },
  modalInput: {
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 10,
    padding: 15,
    fontSize: 16,
    color: '#334155',
    minHeight: 80,
    textAlignVertical: 'top',
    marginBottom: 20,
  },
  modalBotoes: { flexDirection: 'row', justifyContent: 'flex-end', marginTop: 10 },
  modalBtnCancelar: { paddingVertical: 10, paddingHorizontal: 15, marginRight: 10 },
  modalBtnTextCancelar: { color: '#64748B', fontWeight: 'bold', fontSize: 15 },
  modalBtnSalvar: { backgroundColor: '#1E40AF', paddingVertical: 10, paddingHorizontal: 20, borderRadius: 10 },
  modalBtnTextSalvar: { color: '#FFF', fontWeight: 'bold', fontSize: 15 },

  cardItemOrganizado: {
    backgroundColor: '#FFF',
    padding: 15,
    borderRadius: 16,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    elevation: 2,
  },
  btnAdicionarNovo: {
    backgroundColor: '#1E40AF',
    flexDirection: 'row',
    padding: 15,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
  },
  inputSimples: { backgroundColor: '#F1F5F9', borderRadius: 10, padding: 15, marginBottom: 10, fontSize: 15 },

  notificacaoBox: { position: 'absolute', top: 0, left: 15, right: 15, zIndex: 9999, elevation: 15 },
  notificacaoContent: {
    backgroundColor: '#FFF',
    borderRadius: 16,
    padding: 15,
    flexDirection: 'row',
    alignItems: 'center',
    borderLeftWidth: 5,
    borderLeftColor: '#10B981',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
  },
  notificacaoIcon: {
    backgroundColor: '#10B981',
    width: 35,
    height: 35,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  notificacaoTitulo: { fontWeight: 'bold', color: '#1E293B', fontSize: 14 },
  notificacaoTexto: { color: '#64748B', fontSize: 13, marginTop: 2 },

  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 40 },
  loadingText: { marginTop: 12, fontSize: 15, color: '#64748B' },

  searchInput: {
    backgroundColor: '#FFF',
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 15,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 15,
  },
  postCard: {
    backgroundColor: '#FFF',
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    elevation: 2,
  },
  postTitle: { fontSize: 16, fontWeight: 'bold', color: '#1E293B', marginBottom: 6 },
  postBody: { fontSize: 14, color: '#64748B', lineHeight: 20 },
});
